// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.22.4
// source: denoproto/runtime.proto

package denoproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FunctionRuntime_Execute_FullMethodName = "/denoruntime.FunctionRuntime/Execute"
)

// FunctionRuntimeClient is the client API for FunctionRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FunctionRuntimeClient interface {
	Execute(ctx context.Context, in *FunctionRequest, opts ...grpc.CallOption) (*FunctionResponse, error)
}

type functionRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionRuntimeClient(cc grpc.ClientConnInterface) FunctionRuntimeClient {
	return &functionRuntimeClient{cc}
}

func (c *functionRuntimeClient) Execute(ctx context.Context, in *FunctionRequest, opts ...grpc.CallOption) (*FunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FunctionResponse)
	err := c.cc.Invoke(ctx, FunctionRuntime_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionRuntimeServer is the server API for FunctionRuntime service.
// All implementations must embed UnimplementedFunctionRuntimeServer
// for forward compatibility.
type FunctionRuntimeServer interface {
	Execute(context.Context, *FunctionRequest) (*FunctionResponse, error)
	mustEmbedUnimplementedFunctionRuntimeServer()
}

// UnimplementedFunctionRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFunctionRuntimeServer struct{}

func (UnimplementedFunctionRuntimeServer) Execute(context.Context, *FunctionRequest) (*FunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedFunctionRuntimeServer) mustEmbedUnimplementedFunctionRuntimeServer() {}
func (UnimplementedFunctionRuntimeServer) testEmbeddedByValue()                         {}

// UnsafeFunctionRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunctionRuntimeServer will
// result in compilation errors.
type UnsafeFunctionRuntimeServer interface {
	mustEmbedUnimplementedFunctionRuntimeServer()
}

func RegisterFunctionRuntimeServer(s grpc.ServiceRegistrar, srv FunctionRuntimeServer) {
	// If the following call panics, it indicates UnimplementedFunctionRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FunctionRuntime_ServiceDesc, srv)
}

func _FunctionRuntime_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionRuntimeServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionRuntime_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionRuntimeServer).Execute(ctx, req.(*FunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FunctionRuntime_ServiceDesc is the grpc.ServiceDesc for FunctionRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FunctionRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "denoruntime.FunctionRuntime",
	HandlerType: (*FunctionRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _FunctionRuntime_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "denoproto/runtime.proto",
}
