// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.22.4
// source: denoproto/runtime.proto

package denoproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionRequest) Reset() {
	*x = FunctionRequest{}
	mi := &file_denoproto_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionRequest) ProtoMessage() {}

func (x *FunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_denoproto_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionRequest.ProtoReflect.Descriptor instead.
func (*FunctionRequest) Descriptor() ([]byte, []int) {
	return file_denoproto_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FunctionRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *FunctionRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type FunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionResponse) Reset() {
	*x = FunctionResponse{}
	mi := &file_denoproto_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResponse) ProtoMessage() {}

func (x *FunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_denoproto_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResponse.ProtoReflect.Descriptor instead.
func (*FunctionResponse) Descriptor() ([]byte, []int) {
	return file_denoproto_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FunctionResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *FunctionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_denoproto_runtime_proto protoreflect.FileDescriptor

const file_denoproto_runtime_proto_rawDesc = "" +
	"\n" +
	"\x17denoproto/runtime.proto\x12\vdenoruntime\"v\n" +
	"\x0fFunctionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\"c\n" +
	"\x10FunctionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2Y\n" +
	"\x0fFunctionRuntime\x12F\n" +
	"\aExecute\x12\x1c.denoruntime.FunctionRequest\x1a\x1d.denoruntime.FunctionResponseB\rZ\v./denoprotob\x06proto3"

var (
	file_denoproto_runtime_proto_rawDescOnce sync.Once
	file_denoproto_runtime_proto_rawDescData []byte
)

func file_denoproto_runtime_proto_rawDescGZIP() []byte {
	file_denoproto_runtime_proto_rawDescOnce.Do(func() {
		file_denoproto_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_denoproto_runtime_proto_rawDesc), len(file_denoproto_runtime_proto_rawDesc)))
	})
	return file_denoproto_runtime_proto_rawDescData
}

var file_denoproto_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_denoproto_runtime_proto_goTypes = []any{
	(*FunctionRequest)(nil),  // 0: denoruntime.FunctionRequest
	(*FunctionResponse)(nil), // 1: denoruntime.FunctionResponse
}
var file_denoproto_runtime_proto_depIdxs = []int32{
	0, // 0: denoruntime.FunctionRuntime.Execute:input_type -> denoruntime.FunctionRequest
	1, // 1: denoruntime.FunctionRuntime.Execute:output_type -> denoruntime.FunctionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_denoproto_runtime_proto_init() }
func file_denoproto_runtime_proto_init() {
	if File_denoproto_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_denoproto_runtime_proto_rawDesc), len(file_denoproto_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_denoproto_runtime_proto_goTypes,
		DependencyIndexes: file_denoproto_runtime_proto_depIdxs,
		MessageInfos:      file_denoproto_runtime_proto_msgTypes,
	}.Build()
	File_denoproto_runtime_proto = out.File
	file_denoproto_runtime_proto_goTypes = nil
	file_denoproto_runtime_proto_depIdxs = nil
}
