// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.22.4
// source: compute.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Any cell value can be string, number, or boolean
type FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*FieldValue_Num
	//	*FieldValue_Text
	//	*FieldValue_Date
	Kind          isFieldValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_compute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{0}
}

func (x *FieldValue) GetKind() isFieldValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *FieldValue) GetNum() float64 {
	if x != nil {
		if x, ok := x.Kind.(*FieldValue_Num); ok {
			return x.Num
		}
	}
	return 0
}

func (x *FieldValue) GetText() string {
	if x != nil {
		if x, ok := x.Kind.(*FieldValue_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *FieldValue) GetDate() string {
	if x != nil {
		if x, ok := x.Kind.(*FieldValue_Date); ok {
			return x.Date
		}
	}
	return ""
}

type isFieldValue_Kind interface {
	isFieldValue_Kind()
}

type FieldValue_Num struct {
	Num float64 `protobuf:"fixed64,1,opt,name=num,proto3,oneof"`
}

type FieldValue_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type FieldValue_Date struct {
	Date string `protobuf:"bytes,3,opt,name=date,proto3,oneof"` // dd-mm-yyyy format
}

func (*FieldValue_Num) isFieldValue_Kind() {}

func (*FieldValue_Text) isFieldValue_Kind() {}

func (*FieldValue_Date) isFieldValue_Kind() {}

type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 2D flattened values as mixed types
	Values        []*FieldValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Rows          int32         `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"` // optional, for 2D ranges
	Cols          int32         `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_compute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{1}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetValues() []*FieldValue {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Field) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Field) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ComputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inputs        []*Field               `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []string               `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	DocLocation   string                 `protobuf:"bytes,3,opt,name=doc_location,json=docLocation,proto3" json:"doc_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeRequest) Reset() {
	*x = ComputeRequest{}
	mi := &file_compute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeRequest) ProtoMessage() {}

func (x *ComputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeRequest.ProtoReflect.Descriptor instead.
func (*ComputeRequest) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{2}
}

func (x *ComputeRequest) GetInputs() []*Field {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ComputeRequest) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ComputeRequest) GetDocLocation() string {
	if x != nil {
		return x.DocLocation
	}
	return ""
}

type ComputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*Field               `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeResponse) Reset() {
	*x = ComputeResponse{}
	mi := &file_compute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResponse) ProtoMessage() {}

func (x *ComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResponse.ProtoReflect.Descriptor instead.
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{3}
}

func (x *ComputeResponse) GetOutputs() []*Field {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type ExecuteMacrosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocLocation   string                 `protobuf:"bytes,1,opt,name=doc_location,json=docLocation,proto3" json:"doc_location,omitempty"`         // path to .ods file
	Macro1Name    string                 `protobuf:"bytes,2,opt,name=macro1_name,json=macro1Name,proto3" json:"macro1_name,omitempty"`            // e.g. PopulateInputsFromJSON
	Macro1Json    string                 `protobuf:"bytes,3,opt,name=macro1_json,json=macro1Json,proto3" json:"macro1_json,omitempty"`            // JSON string input
	Macro2Name    string                 `protobuf:"bytes,4,opt,name=macro2_name,json=macro2Name,proto3" json:"macro2_name,omitempty"`            // e.g. ExportOutputSheetToPDF
	Macro2PdfPath string                 `protobuf:"bytes,5,opt,name=macro2_pdf_path,json=macro2PdfPath,proto3" json:"macro2_pdf_path,omitempty"` // full PDF output path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMacrosRequest) Reset() {
	*x = ExecuteMacrosRequest{}
	mi := &file_compute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMacrosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMacrosRequest) ProtoMessage() {}

func (x *ExecuteMacrosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMacrosRequest.ProtoReflect.Descriptor instead.
func (*ExecuteMacrosRequest) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteMacrosRequest) GetDocLocation() string {
	if x != nil {
		return x.DocLocation
	}
	return ""
}

func (x *ExecuteMacrosRequest) GetMacro1Name() string {
	if x != nil {
		return x.Macro1Name
	}
	return ""
}

func (x *ExecuteMacrosRequest) GetMacro1Json() string {
	if x != nil {
		return x.Macro1Json
	}
	return ""
}

func (x *ExecuteMacrosRequest) GetMacro2Name() string {
	if x != nil {
		return x.Macro2Name
	}
	return ""
}

func (x *ExecuteMacrosRequest) GetMacro2PdfPath() string {
	if x != nil {
		return x.Macro2PdfPath
	}
	return ""
}

type ExecuteMacrosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // error or success info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMacrosResponse) Reset() {
	*x = ExecuteMacrosResponse{}
	mi := &file_compute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMacrosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMacrosResponse) ProtoMessage() {}

func (x *ExecuteMacrosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMacrosResponse.ProtoReflect.Descriptor instead.
func (*ExecuteMacrosResponse) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteMacrosResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteMacrosResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_compute_proto protoreflect.FileDescriptor

const file_compute_proto_rawDesc = "" +
	"\n" +
	"\rcompute.proto\x12\vspreadsheet\"T\n" +
	"\n" +
	"FieldValue\x12\x12\n" +
	"\x03num\x18\x01 \x01(\x01H\x00R\x03num\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12\x14\n" +
	"\x04date\x18\x03 \x01(\tH\x00R\x04dateB\x06\n" +
	"\x04kind\"t\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x06values\x18\x02 \x03(\v2\x17.spreadsheet.FieldValueR\x06values\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\x05R\x04cols\"y\n" +
	"\x0eComputeRequest\x12*\n" +
	"\x06inputs\x18\x01 \x03(\v2\x12.spreadsheet.FieldR\x06inputs\x12\x18\n" +
	"\aoutputs\x18\x02 \x03(\tR\aoutputs\x12!\n" +
	"\fdoc_location\x18\x03 \x01(\tR\vdocLocation\"?\n" +
	"\x0fComputeResponse\x12,\n" +
	"\aoutputs\x18\x01 \x03(\v2\x12.spreadsheet.FieldR\aoutputs\"\xc4\x01\n" +
	"\x14ExecuteMacrosRequest\x12!\n" +
	"\fdoc_location\x18\x01 \x01(\tR\vdocLocation\x12\x1f\n" +
	"\vmacro1_name\x18\x02 \x01(\tR\n" +
	"macro1Name\x12\x1f\n" +
	"\vmacro1_json\x18\x03 \x01(\tR\n" +
	"macro1Json\x12\x1f\n" +
	"\vmacro2_name\x18\x04 \x01(\tR\n" +
	"macro2Name\x12&\n" +
	"\x0fmacro2_pdf_path\x18\x05 \x01(\tR\rmacro2PdfPath\"K\n" +
	"\x15ExecuteMacrosResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb2\x01\n" +
	"\x12SpreadsheetService\x12D\n" +
	"\aCompute\x12\x1b.spreadsheet.ComputeRequest\x1a\x1c.spreadsheet.ComputeResponse\x12V\n" +
	"\rExecuteMacros\x12!.spreadsheet.ExecuteMacrosRequest\x1a\".spreadsheet.ExecuteMacrosResponseB)Z'github.com/FuturaInsTech/gi-excel/protob\x06proto3"

var (
	file_compute_proto_rawDescOnce sync.Once
	file_compute_proto_rawDescData []byte
)

func file_compute_proto_rawDescGZIP() []byte {
	file_compute_proto_rawDescOnce.Do(func() {
		file_compute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compute_proto_rawDesc), len(file_compute_proto_rawDesc)))
	})
	return file_compute_proto_rawDescData
}

var file_compute_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_compute_proto_goTypes = []any{
	(*FieldValue)(nil),            // 0: spreadsheet.FieldValue
	(*Field)(nil),                 // 1: spreadsheet.Field
	(*ComputeRequest)(nil),        // 2: spreadsheet.ComputeRequest
	(*ComputeResponse)(nil),       // 3: spreadsheet.ComputeResponse
	(*ExecuteMacrosRequest)(nil),  // 4: spreadsheet.ExecuteMacrosRequest
	(*ExecuteMacrosResponse)(nil), // 5: spreadsheet.ExecuteMacrosResponse
}
var file_compute_proto_depIdxs = []int32{
	0, // 0: spreadsheet.Field.values:type_name -> spreadsheet.FieldValue
	1, // 1: spreadsheet.ComputeRequest.inputs:type_name -> spreadsheet.Field
	1, // 2: spreadsheet.ComputeResponse.outputs:type_name -> spreadsheet.Field
	2, // 3: spreadsheet.SpreadsheetService.Compute:input_type -> spreadsheet.ComputeRequest
	4, // 4: spreadsheet.SpreadsheetService.ExecuteMacros:input_type -> spreadsheet.ExecuteMacrosRequest
	3, // 5: spreadsheet.SpreadsheetService.Compute:output_type -> spreadsheet.ComputeResponse
	5, // 6: spreadsheet.SpreadsheetService.ExecuteMacros:output_type -> spreadsheet.ExecuteMacrosResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_compute_proto_init() }
func file_compute_proto_init() {
	if File_compute_proto != nil {
		return
	}
	file_compute_proto_msgTypes[0].OneofWrappers = []any{
		(*FieldValue_Num)(nil),
		(*FieldValue_Text)(nil),
		(*FieldValue_Date)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compute_proto_rawDesc), len(file_compute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compute_proto_goTypes,
		DependencyIndexes: file_compute_proto_depIdxs,
		MessageInfos:      file_compute_proto_msgTypes,
	}.Build()
	File_compute_proto = out.File
	file_compute_proto_goTypes = nil
	file_compute_proto_depIdxs = nil
}
