// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.22.4
// source: proto/compute.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpreadsheetService_Compute_FullMethodName = "/spreadsheet.SpreadsheetService/Compute"
)

// SpreadsheetServiceClient is the client API for SpreadsheetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpreadsheetServiceClient interface {
	Compute(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*ComputeResponse, error)
}

type spreadsheetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpreadsheetServiceClient(cc grpc.ClientConnInterface) SpreadsheetServiceClient {
	return &spreadsheetServiceClient{cc}
}

func (c *spreadsheetServiceClient) Compute(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*ComputeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeResponse)
	err := c.cc.Invoke(ctx, SpreadsheetService_Compute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpreadsheetServiceServer is the server API for SpreadsheetService service.
// All implementations must embed UnimplementedSpreadsheetServiceServer
// for forward compatibility.
type SpreadsheetServiceServer interface {
	Compute(context.Context, *ComputeRequest) (*ComputeResponse, error)
	mustEmbedUnimplementedSpreadsheetServiceServer()
}

// UnimplementedSpreadsheetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpreadsheetServiceServer struct{}

func (UnimplementedSpreadsheetServiceServer) Compute(context.Context, *ComputeRequest) (*ComputeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compute not implemented")
}
func (UnimplementedSpreadsheetServiceServer) mustEmbedUnimplementedSpreadsheetServiceServer() {}
func (UnimplementedSpreadsheetServiceServer) testEmbeddedByValue()                            {}

// UnsafeSpreadsheetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpreadsheetServiceServer will
// result in compilation errors.
type UnsafeSpreadsheetServiceServer interface {
	mustEmbedUnimplementedSpreadsheetServiceServer()
}

func RegisterSpreadsheetServiceServer(s grpc.ServiceRegistrar, srv SpreadsheetServiceServer) {
	// If the following call panics, it indicates UnimplementedSpreadsheetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpreadsheetService_ServiceDesc, srv)
}

func _SpreadsheetService_Compute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpreadsheetServiceServer).Compute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpreadsheetService_Compute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpreadsheetServiceServer).Compute(ctx, req.(*ComputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpreadsheetService_ServiceDesc is the grpc.ServiceDesc for SpreadsheetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpreadsheetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spreadsheet.SpreadsheetService",
	HandlerType: (*SpreadsheetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compute",
			Handler:    _SpreadsheetService_Compute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/compute.proto",
}
